### ISSUE TITLE
Uses a deprecated aws-sdk API...

### ISSUE THREAD

**Issue by tvanriper** [simonmcallister0210/cognito-srp-helper#13]
AWS has deprecated version 2 of the aws-sdk API this library uses, as announced here:

https://aws.amazon.com/blogs/developer/deprecation-schedule-for-aws-sdk-for-ruby-v2/

They have moved to a collection of APIs that start with '@aws-sdk' (version 3), as detailed here:

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/index.html

Consequently, any discovered security issues within version 2 of the aws-sdk will not be patched, which for something like this which provides support for authentication, could be problematic.

**Comment by simonmcallister0210** [comment]
Good spot! At the moment it's only being used for Typescript types so I imagine there would be less risk, but you're right it's not ideal. We should be using [@aws-sdk/types](https://www.npmjs.com/package/@aws-sdk/types)

I'll push out a fix later this week

**Comment by simonmcallister0210** [comment]
Resolved in v2.1.0
