### ISSUE TITLE
Error During SRP Authentication Using "User_SRP_Auth"

### ISSUE THREAD

**Issue by varuna-peiris** [simonmcallister0210/cognito-srp-helper#39]
I am trying to authenticate a user using the User_SRP_Auth authflow from the repository. While following the steps provided, I encountered an error.
Steps to Reproduce:
	1. Cloned the repository.
	2. Use the repo by following the code.
``  
import CognitoSrpHelper from "./src/cognito-srp-helper";
import { CognitoIdentityProviderClient, InitiateAuthCommand, RespondToAuthChallengeCommand } from "@aws-sdk/client-cognito-identity-provider";

const username = "xxxxxx";
const password = "xxxxxx";
const clientId = "xxxxxxxxxxxxxxxxxxxxxx";
const secretId = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
const poolId = "xxxxxxx_xxxxxxxxx";

const secretHash = CognitoSrpHelper.createSecretHash(username, clientId, secretId);
const srpSession = CognitoSrpHelper.createSrpSession(username, password, poolId, false);

async function run() {
  try {
    const initiateAuthRes = await CognitoIdentityProviderClient.send(
      new InitiateAuthCommand(
        CognitoSrpHelper.wrapInitiateAuth(srpSession, {
          ClientId: clientId,
          AuthFlow: "USER_SRP_AUTH",
          AuthParameters: {
            CHALLENGE_NAME: "SRP_A",
            SECRET_HASH: secretHash,
            USERNAME: username,
          },
        }),
      ),
    );

    const signedSrpSession = CognitoSrpHelper.signSrpSession(srpSession, initiateAuthRes);

    const respondToAuthChallengeRes = await CognitoIdentityProviderClient.send(
      new RespondToAuthChallengeCommand(
        CognitoSrpHelper.wrapAuthChallenge(signedSrpSession, {
          ClientId: clientId,
          ChallengeName: "PASSWORD_VERIFIER",
          ChallengeResponses: {
            SECRET_HASH: secretHash,
            USERNAME: username,
          },
        }),
      ),
    );
  } catch (err) {
    console.error(err);
  }
}

run();
 ``
	4. Run the code on Windows cmd
		$ node <filename.js>
When I ran this (windows 10, Node.js v20.16.0), I encountered the following error:
![image](https://github.com/user-attachments/assets/060d15ee-be2f-4a19-bfbb-70e5f99d1c15)

Please guide me, in completing the SRP authentication process successfully, resulting in a valid authentication response using your repo.

I appreciate any help you can provide.

Thanks in advance.

**Comment by simonmcallister0210** [comment]
Hey Varuna, thanks for checking out the project 🙂 

Importing `src/*` files won't work if you're importing inside a `.js` file, because the project is written in TypeScript. It needs to be compiled before you can import it in JavaScript

If you build the project with `npm run build` then you should be able to import it by refering to the package name:

```js
import * as CognitoSrpHelper from "cognito-srp-helper";

// . . .
```

Let me know if that works for you

**Comment by varuna-peiris** [comment]
Thank you for your response.
I tried what you suggested steps but the error is still the same. Here I attached a screenshot for your reference.
![image](https://github.com/user-attachments/assets/72629d2b-b074-470e-9313-333bbc661737)

**Comment by simonmcallister0210** [comment]
That's odd 🤔 

Did you update the import statement? from:

`import CognitoSrpHelper from "./src/cognito-srp-helper";`

.. to ..

`import * as CognitoSrpHelper from "cognito-srp-helper";`

**Comment by varuna-peiris** [comment]
Yes, I updated it.
Now I did the following to a new clone and the error was changed. Here I attached a screenshot for your reference.
![image](https://github.com/user-attachments/assets/8bf31f1f-8a48-44c5-b8bf-d3cd6103af46)

**Comment by simonmcallister0210** [comment]
Oh, that's to do with CognitoIdentityProviderClient. You need to instantiate the client first:

```js
const cognitoIdentityProviderClient = new CognitoIdentityProviderClient({
  region: "eu-west-2", // <-- this should be the AWS region
});  
```

Then you can call send on the instance you created:

```js
const respondToAuthChallengeRes = await cognitoIdentityProviderClient.send(
  // . . .
);
```

**Comment by varuna-peiris** [comment]
I ran the code applying the above changes and it runs without errors. But it does not appear to pop up or anything for the challenge. I've attached a screenshot for you to look over.
![image](https://github.com/user-attachments/assets/ff14d1ed-3cf9-48be-888c-5aaf699ba6f2)
Please guide me.

**Comment by simonmcallister0210** [comment]
Ah, you may just need to log something to the console

Since a lot of these questions are unrelated to the package itself I'll close this issue. But if any issues specific to the package does come up feel free to open up this issue again
