### ISSUE TITLE
Import errors with --moduleResolution 'node16' or 'nodenext'

### ISSUE THREAD

**Issue by pappnase99** [simonmcallister0210/cognito-srp-helper#41]
My Typescript project is set up with both these settings in the tsconfig.json: `"module": "NodeNext", "moduleResolution": "NodeNext"`.

I tried to import functions from cognito-srp-helper like 'createSrpSession' but this produced the error "Module 'cognito-srp-helper' has no exported member 'createSrpSession'. When I looked into the file 'node_modules/cognito-srp-helper/dist/types/index.d.ts' I see multiple errors like 
```
Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

1 export * from "./cognito-srp-helper";
```
and so on. I could manually fix these by appending the '.ts' extension to the exports and make the compiler happy. Same with 'cognito-srp-helper.d.ts' file.

**Comment by simonmcallister0210** [comment]
Really I should be using `moduleResolution: "bundler"`... lesson learned

If I update it now I'm worried it'll be a breaking change. Need to do some research on the impact of changing `moduleResolution`. Worst case I'll queue the change up for the next major release

**Comment by DmitryLyubetsky** [comment]
Hello @simonmcallister0210 is there any progress for this issue? The solution from author are works, but we are not want to patch or fork from this repo.

**Comment by simonmcallister0210** [comment]
Would be risky making this change in a minor version update. What I could do is push a beta release of the package that would contain the fix. Would that work as a temporary solution? (at least until v3 is released)

**Comment by DmitryLyubetsky** [comment]
@simonmcallister0210 sounds good, would been really appreciated if you do it :)

**Comment by simonmcallister0210** [comment]
Looking at the fix I've just bundled the declaration files into file to avoid import statements. This shouldn't cause any issues for existing users so should be safe for release in v2

I've published a beta version under [2.3.2-beta-v1](https://www.npmjs.com/package/cognito-srp-helper/v/2.3.2-beta-v1). Let me know if there are any issue. If there's no issues I'll merge it in

**Comment by DmitryLyubetsky** [comment]
@simonmcallister0210 hey, sorry for the late reply, I check the beta version, and it's works without issues, thanks.

**Comment by simonmcallister0210** [comment]
Cool I'll merge it in tonight

**Comment by simonmcallister0210** [comment]
Just published. Should be live under the latest patch [2.3.2](https://www.npmjs.com/package/cognito-srp-helper/v/2.3.2)
